name: dea
channels:
  - conda-forge
dependencies:
  # dataframes
  - pandas
  - geopandas

  # ui
  - streamlit
  - bokeh==2.2.3

  # filesystem
  - fsspec
  - s3fs
  - python-dotenv

  # dev & testing
  - pytest
  - black
  - mypy

  - pip
  - pip:
    - streamlit-bokeh-events 
    - git+https://github.com/codema-dev/rc-building-model